# _welcome:
#     pattern:  /
#     defaults: { _controller: AcmeDemo:Welcome:index }

_demo_secured:
    resource: "@AcmeDemo/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemo/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

fos_user_security:
    resource: @FOSUser/Resources/config/routing/security.xml

fos_user_user:
    resource: @FOSUser/Resources/config/routing/user.xml
    prefix: /user
    
app_account:
    resource: @AppAccount/Resources/config/routing.yml

app_site:
    resource: @AppSite/Resources/config/routing.yml

app_web:
    resource: @AppWeb/Resources/config/routing.yml